### ISSUE TITLE
Hot Restart not working on iOS

### ISSUE THREAD

**Issue by glemartret** [SocketMobile/capturesdk_flutter#8]
Using the example app on iOS, and doing a Hot Restart of the app, the openClient never returns and crash the App

**Comment by vtjiles** [comment]
I have the same issue. It's pretty much unusable for development. Are there any plans to address this issue or can the team provide guidance on how to make this work across restarts on iOS?

**Comment by sdksupport-socketmobile** [comment]
Hi @vtjiles apologies for the late reply. Unfortunately we haven't been able to work on this yet as there have been other features we've been working on but we plan to address this starting next week. We'll reach back out here with any updates.

**Comment by sdksupport-socketmobile** [comment]
HI @vtjiles, sorry for not following up earlier as we hit a few blocks with some other items and are still working on this one. We are hoping to have a resolution for this by end of week and will keep you posted!

**Comment by cyrille-socket** [comment]
Hi @glemartret and @vtjiles,

we have just released the new version 1.5.19 that is now available on our [Developers Portal](https://www.socketmobile.com/dev-portal/portal) that fixes this Hot Restart issue. 

Thank you for your patience and let us know if that works for you.
